FROM node:22-bookworm-slim

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install

COPY vite.config.ts ./
COPY tsconfig.json ./
COPY tsconfig.app.json ./
COPY tsconfig.node.json ./
COPY index.html ./

EXPOSE 8080

CMD ["npm", "run", "dev"]
